export const colors = {
  UNBLEACHED_SILK: '#FED7D2',
  UNBLEACHED_SILK_50: '#FED7D250',
  PALE_CHESTNUT: '#ECB4B4',
  PALE_CORNFLOWER_BLUE: '#B4D0EC',
  GREY: '#808080',
  PALE_GREY: '#C0C0C0',
  BRIGHT_GREY: '#ECECEC',
}

